# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 24d8e203c8c88feb88f0857bdf171766ebdc9f4f140989c7d4174533901fe504c7c175bfbd95dd64c68555128b4c58506361dd19820b02b8146bc2ee044b128d

test:
  secret_key_base: 7ef4d15af8b646cd09416c3311c8357971ff778b062c7c889bf38cc25cf56e556d9edbc9563119c3c0455aae4d7cd7e58ba259ca898454fff13b0bfc7ac9acc0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
